### ISSUE TITLE
Separate reader/writer

### ISSUE THREAD

**Issue by brndnmtthws** [atuk721/redis-cluster-rs#3]
Thanks for your work on the project. I've been browsing the code, and I'm trying to figure out the correct way to separate readers and writers. My understanding is that clients should enable the [READONLY](https://redis.io/commands/readonly) mode. Perhaps this should be supported by the client?

Ideally I want to make sure all reads go to replicas (or slaves), whereas all writes go to masters.

**Comment by atuk721** [comment]
Hello,
I am sorry for replying you late.

I think new option that indicates whether read only or not should be passed when client is opened.
When it is passed, replica address will be used.
In that case, that client will be only used for read only.
When you need to write, you need to create other client with no read only option.

In any case, I think we need to decide that how we decide to select replica when we have multiple replicas.
We can simply use a one of fixed index or selecting randomly.
But if it needs to balance load, I think we need more specific option.

**Comment by brndnmtthws** [comment]
For the read replicas, I think doing a random choice on initialization is reasonable. It's effectively round-robin.

**Comment by atuk721** [comment]
I got it.
Please wait a week or please PR.

**Comment by atuk721** [comment]
Publish completed.
